cnf: works with command-not-found and pkginfo, if either is installed

diff --git a/ksh/.config/ksh/funcs/cnf b/ksh/.config/ksh/funcs/cnf
--- a/ksh/.config/ksh/funcs/cnf
+++ b/ksh/.config/ksh/funcs/cnf
@@ -1,17 +1,24 @@
 #!/usr/local/bin/ksh
 function cnf  {
+
   cmd=$1
-  FUNCNEST=10
-  typeset -a pkgs
+  # check if we can use command-not-found or pkgfile and make the
+  # appropriate call
+  if [[ -f /usr/lib/command-not-found ]]; then
+       /usr/lib/command-not-found $cmd
+  elif whence -q pkgfile; then
+      FUNCNEST=10
+      typeset -a pkgs
 
-  pkgs=$(pkgfile -bv -- "$cmd" 2>/dev/null)
+      pkgs=$(pkgfile -bv -- "$cmd" 2>/dev/null)
 
-  if (( ${#pkgs[*]} )); then
-    printf '%s may be found in the following packages:\n' "$cmd"
-    printf '  %s\n' "${pkgs[@]}"
-  else
-    printf "ksh: %s: command not found\n" "$cmd"
-  fi >&2
+      if (( ${#pkgs[*]} )); then
+        printf '%s may be found in the following packages:\n' "$cmd"
+        printf '  %s\n' "${pkgs[@]}"
+      else
+        printf "ksh: %s: command not found\n" "$cmd"
+      fi >&2
 
-  return 127
+      return 127
+  fi
 }
